services:
  int-proxy:
    build: .
    image: int-caddy
    container_name: int-proxy
    user: 190:190
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/int-proxy/.env
    environment:
      MY_DOMAIN: "${MY_DOMAIN:?}"
      PROXMOX_IP: "${PROXMOX_IP:?}"
      OPNSENSE_LAN_IP: "${OPNSENSE_LAN_IP:?}"
    ports:
      - "${HOST_IP:?}:80:80"
      - "${HOST_IP:?}:443:443/tcp"
      - "${HOST_IP:?}:443:443/udp"
    volumes:
      - ./conf:/etc/caddy:ro
      - ../../utils/caddy:/etc/caddy-configs:ro
      - ${CONFIGS_DIR:?}/error-pages/dist:/srv/error-pages:ro
      - ${FAST_VOLUMES:?}/int-proxy/caddy-data:/data
      - ${FAST_VOLUMES:?}/int-proxy/caddy-config:/config
    networks:
      outgoing:
        ipv4_address: 172.19.0.130

networks:
  outgoing:
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.129
