services:
  pihole:
    image: pihole/pihole:2025.08.0
    container_name: pihole
    user: 0:0 # required
    restart: unless-stopped
    environment:
      PIHOLE_UID: "0" # required
      PIHOLE_GID: "0" # required
      TZ: "Europe/Zurich"
      FTLCONF_webserver_api_password: ""
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_rateLimit_count: "0"
      FTLCONF_dns_rateLimit_interval: "0"
    ports:
      - "${HOST_IP:?}:53:53/tcp"
      - "${HOST_IP:?}:53:53/udp"
    volumes:
      - ${SLOW_VOLUMES:?}/pihole/config:/etc/pihole
    networks:
      net-pihole:
        ipv4_address: 172.19.3.4
      outgoing:
        ipv4_address: 172.19.3.130
    labels:
      alloy.enable_logging: "true"
      homepage.group: "Internal"
      homepage.name: "Pi-hole"
      homepage.icon: "pi-hole.png"
      homepage.instance.internal.href: "https://pihole.${MY_DOMAIN:?}"
      homepage.description: "Network-wide ad blocker."
      homepage.instance.internal.widget.type: "protectedpihole"
      homepage.instance.internal.widget.url: "https://pihole.${MY_DOMAIN:?}"
      homepage.instance.internal.widget.version: "6"
      homepage.instance.internal.widget.username: "${INT_HOMEPAGE_AUTHENTIK_USERNAME:?}"
      homepage.instance.internal.widget.password: "${INT_HOMEPAGE_AUTHENTIK_PASSWORD:?}"

networks:
  net-pihole:
    external: true
  outgoing:
    ipam:
      config:
        - subnet: 172.19.3.128/25
          gateway: 172.19.3.129
