services:
  prometheus:
    image: prom/prometheus:v3.6.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.size=1TB"
    container_name: prometheus
    user: 210:210
    read_only: true
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${SLOW_VOLUMES:?}/prometheus/data:/prometheus
    networks:
      prom-wg:
        ipv4_address: 172.21.1.2
      prom-ext-caddy:
        ipv4_address: 172.21.2.2
      prom-int-caddy:
        ipv4_address: 172.21.3.2
      prom-authentik:
        ipv4_address: 172.21.4.2
      prom-grafana:
        ipv4_address: 172.21.5.2
      prom-cadvisor:
        ipv4_address: 172.21.6.2
      prom-node-exporter:
        ipv4_address: 172.21.7.2
      prom-jellyfin:
        ipv4_address: 172.21.8.2
      prom-flaresolverr:
        ipv4_address: 172.21.9.2
      prom-qui:
        ipv4_address: 172.21.10.2
      prom-autobrr:
        ipv4_address: 172.21.11.2
      prom-scraparr:
        ipv4_address: 172.21.12.2
      prom-int-homepage:
        ipv4_address: 172.21.13.2
      prom-unpackerr:
        ipv4_address: 172.21.14.2
    labels:
      alloy.enable_logging: "true"
      homepage.group: "Monitoring"
      homepage.name: "Prometheus"
      homepage.icon: "prometheus.png"
      homepage.description: "Monitoring system and time series database."
      homepage.instance.internal.widget.type: "prometheus"
      homepage.instance.internal.widget.url: "http://prometheus:9090"
      homepage.weight: "2"

networks:
  prom-wg:
    external: true
  prom-ext-caddy:
    external: true
  prom-int-caddy:
    external: true
  prom-authentik:
    external: true
  prom-grafana:
    external: true
  prom-cadvisor:
    external: true
  prom-node-exporter:
    external: true
  prom-jellyfin:
    external: true
  prom-flaresolverr:
    external: true
  prom-qui:
    external: true
  prom-autobrr:
    external: true
  prom-scraparr:
    external: true
  prom-int-homepage:
    external: true
  prom-unpackerr:
    external: true
