global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "wireguard"
    static_configs:
      - targets: ["wireguard:9586"]

  - job_name: "ext-proxy"
    static_configs:
      - targets: ["ext-proxy:2019"]

  - job_name: "int-proxy"
    static_configs:
      - targets: ["int-proxy:2019"]

  - job_name: "authentik"
    static_configs:
      - targets: ["authentik-server:9300"]

  - job_name: "jellyfin"
    static_configs:
      - targets: ["jellyfin:8096"]

  - job_name: "flaresolverr"
    static_configs:
      - targets: ["flaresolverr:8192"]

  - job_name: "qui"
    static_configs:
      - targets: ["qui:9074"]

  - job_name: "autobrr"
    static_configs:
      - targets: ["autobrr:9074"]
