services:
  int-homepage:
    build: ${SERVICES_DIR:?}/homepage
    image: homepage
    container_name: int-homepage
    user: 1192:1192
    read_only: true
    restart: unless-stopped
    depends_on:
      - int-dockerproxy
    environment:
      PUID: "1192"
      PGID: "1192"
      HOMEPAGE_ALLOWED_HOSTS: "home.${MY_DOMAIN:?}"
      LOG_TARGETS: "stdout"
    volumes:
      - ${CONFIGS_DIR:?}/int-homepage/config:/app/config:ro
      - ${CONFIGS_DIR:?}/webmedia/images/background-image.jpg:/app/public/images/background-image.jpg:ro
      - ${CONFIGS_DIR:?}/webmedia/icons/dabloon.png:/app/public/icons/dabloon.png:ro
      - ${CONFIGS_DIR:?}/webmedia/icons/homepage-favicon.ico:/app/public/favicon.ico:ro
      - ${CONFIGS_DIR:?}/webmedia/icons/homepage-favicon.ico:/app/public/favicon-32x32.png:ro
      - ${FAST_VOLUMES:?}/int-homepage/writable:/app/.next/server/pages
    networks:
      prom-int-homepage:
        ipv4_address: 172.21.13.3
      net-int-homepage:
        ipv4_address: 172.19.2.4
      internal:
        ipv4_address: 172.19.2.66
      outgoing:
        ipv4_address: 172.19.2.130
    extra_hosts:
      # Resolve internal domains to int-proxy otherwise firewall blocks them
      - "pihole.${MY_DOMAIN:?}=172.19.2.2"
      - "grafana.${MY_DOMAIN:?}=172.19.2.2"
      - "radarr.${MY_DOMAIN:?}=172.19.2.2"
      - "sonarr.${MY_DOMAIN:?}=172.19.2.2"
      - "prowlarr.${MY_DOMAIN:?}=172.19.2.2"
      - "torrents.${MY_DOMAIN:?}=172.19.2.2"
      - "autobrr.${MY_DOMAIN:?}=172.19.2.2"
    labels:
      alloy.enable_logging: "true"
      homepage.group: "Internal"
      homepage.name: "Internal Homepage"
      homepage.icon: "homepage.png"
      homepage.instance.internal.href: "https://${MY_DOMAIN:?}"
      homepage.instance.internal.description: "This very homepage!"
      homepage.instance.external.description: "A hidden homepage... displaying more details about every service!"

  int-dockerproxy:
    image: tecnativa/docker-socket-proxy:v0.4.1
    container_name: int-dockerproxy
    user: 0:0 # required to read docker socket
    read_only: true
    restart: unless-stopped
    environment:
      CONTAINERS: 1
    volumes:
      - /run/rootlesskit/docker.socket:/var/run/docker.sock:ro
    networks:
      internal:
        ipv4_address: 172.19.2.67
    tmpfs:
      - /run
      - /tmp
    labels:
      alloy.enable_logging: "true"

networks:
  prom-int-homepage:
    external: true
  net-int-homepage:
    external: true
  internal:
    internal: true
    ipam:
      config:
        - subnet: 172.19.2.64/26
          gateway: 172.19.2.65
  outgoing:
    ipam:
      config:
        - subnet: 172.19.2.128/26
          gateway: 172.19.2.129
