services:
  ext-homepage:
    build: ${SERVICES_DIR:?}/homepage
    image: homepage
    container_name: ext-homepage
    user: 1182:1182
    read_only: true
    restart: unless-stopped
    depends_on:
      - ext-dockerproxy
    environment:
      PUID: "1182"
      PGID: "1182"
      HOMEPAGE_ALLOWED_HOSTS: "${MY_DOMAIN:?}"
      LOG_TARGETS: "stdout"
      HOMEPAGE_VAR_MY_DOMAIN: "${MY_DOMAIN:?}"
    volumes:
      - ${CONFIGS_DIR:?}/ext-homepage/config:/app/config:ro
      - ${CONFIGS_DIR:?}/webmedia/images/background-image.jpg:/app/public/images/background-image.jpg:ro
      - ${CONFIGS_DIR:?}/webmedia/icons/dabloon.png:/app/public/icons/dabloon.png:ro
      - ${CONFIGS_DIR:?}/webmedia/icons/homepage-favicon.ico:/app/public/favicon.ico:ro
      - ${CONFIGS_DIR:?}/webmedia/icons/homepage-favicon.ico:/app/public/favicon-32x32.png:ro
      - ${FAST_VOLUMES:?}/ext-homepage/writable:/app/.next/server/pages
    networks:
      net-ext-homepage:
        ipv4_address: 172.18.2.4
      internal:
        ipv4_address: 172.18.2.66
      outgoing:
        ipv4_address: 172.18.2.130
    labels:
      homepage.group: "External"
      homepage.name: "External Homepage"
      homepage.icon: "homepage.png"
      homepage.instance.external.href: "https://${MY_DOMAIN:?}"
      homepage.instance.external.description: "This very homepage!"
      homepage.instance.internal.description: "The external homepage... displaying only a subset of available information!"

  ext-dockerproxy:
    image: tecnativa/docker-socket-proxy:v0.4.1
    container_name: ext-dockerproxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
    volumes:
      - /run/rootlesskit/docker.socket:/var/run/docker.sock:ro
    networks:
      internal:
        ipv4_address: 172.18.2.67

networks:
  net-ext-homepage:
    external: true
  internal:
    internal: true
    ipam:
      config:
        - subnet: 172.18.2.64/26
  outgoing:
    ipam:
      config:
        - subnet: 172.18.2.128/26
          gateway: 172.18.2.129
