services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    user: 0:0 # required to read docker socket
    read_only: true
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /run/rootlesskit/docker.socket:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /home/dockeruser/.local/share/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      prom-cadvisor:
        ipv4_address: 172.21.6.3
    labels:
      alloy.enable_logging: "true"
      homepage.group: "Monitoring"
      homepage.name: "cAdvisor"
      homepage.icon: "cadvisor.png"
      homepage.description: "Container Advisor (cAdvisor) provides container resource usage and performance characteristics."
      homepage.weight: "5"

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.9.1
    command: "--path.rootfs=/host"
    container_name: node-exporter
    user: 2217:2217
    read_only: true
    restart: unless-stopped
    pid: "host"
    volumes:
      - /:/host:ro,rslave
    networks:
      prom-node-exporter:
        ipv4_address: 172.21.7.3
    labels:
      alloy.enable_logging: "true"
      homepage.group: "Monitoring"
      homepage.name: "Node Exporter"
      homepage.icon: "prometheus.png"
      homepage.description: "Prometheus exporter for hardware and OS metrics exposed by *NIX kernels."
      homepage.weight: "6"

networks:
  prom-cadvisor:
    external: true
  prom-node-exporter:
    external: true
