services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    container_name: authentik-postgresql
    user: 1184:1184
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/authentik/.env-postgresql
    volumes:
      - ${SLOW_VOLUMES:?}/authentik/database:/var/lib/postgresql/data
    networks:
      internal:
        ipv4_address: 172.18.4.66
    tmpfs:
      - /var/run/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    labels:
      alloy.enable_logging: "true"

  server:
    image: ghcr.io/goauthentik/server:2025.10.0
    command: server
    container_name: authentik-server
    user: 3184:184
    read_only: true
    restart: unless-stopped
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - ${SECRETS_DIR:?}/authentik/.env-authentik
    volumes:
      - ${SLOW_VOLUMES:?}/authentik/media:/media
      - ${CONFIGS_DIR:?}/webmedia/images/background-image.jpg:/media/background-image.jpg:ro
      - ${SLOW_VOLUMES:?}/authentik/templates:/templates
    networks:
      prom-authentik:
        ipv4_address: 172.21.4.3
      net-authentik:
        ipv4_address: 172.18.4.4
      internal:
        ipv4_address: 172.18.4.67
      outgoing:
        ipv4_address: 172.18.4.130
    labels:
      alloy.enable_logging: "true"
      homepage.group: "External"
      homepage.name: "Authentik"
      homepage.icon: "authentik.png"
      homepage.href: "https://auth.${MY_DOMAIN:?}"
      homepage.description: "A self-hosted SSO and identity provider."
      homepage.instance.internal.widget.type: "authentik"
      homepage.instance.internal.widget.url: "https://auth.${MY_DOMAIN:?}"
      homepage.instance.internal.widget.key: "${INT_HOMEPAGE_AUTHENTIK_API_KEY:?}"
      homepage.instance.internal.widget.version: "2"

  worker:
    image: ghcr.io/goauthentik/server:2025.10.0
    command: worker
    container_name: authentik-worker
    user: 4184:184
    read_only: true
    restart: unless-stopped
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - ${SECRETS_DIR:?}/authentik/.env-authentik
    volumes:
      - ${SLOW_VOLUMES:?}/authentik/media:/media
      - ${CONFIGS_DIR:?}/webmedia/images/background-image.jpg:/media/background-image.jpg
      - ${SLOW_VOLUMES:?}/authentik/templates:/templates
    networks:
      internal:
        ipv4_address: 172.18.4.68
      outgoing:
        ipv4_address: 172.18.4.131
    tmpfs:
      - /certs
    labels:
      alloy.enable_logging: "true"

networks:
  prom-authentik:
    external: true
  net-authentik:
    external: true
  internal:
    internal: true
    ipam:
      config:
        - subnet: 172.18.4.64/26
          gateway: 172.18.4.65
  outgoing:
    ipam:
      config:
        - subnet: 172.18.4.128/26
          gateway: 172.18.4.129
