services:
  ext-proxy:
    build: .
    image: ext-caddy
    container_name: ext-proxy
    user: 180:180
    read_only: true
    restart: unless-stopped
    environment:
      MY_DOMAIN: "${MY_DOMAIN:?}"
      OPNSENSE_SUBNET_IP: "${OPNSENSE_SUBNET_IP:?}"
    ports:
      - "${HOST_IP:?}:8080:80"
      - "${HOST_IP:?}:8443:443/tcp"
      - "${HOST_IP:?}:8443:443/udp"
    volumes:
      - ./conf:/etc/caddy:ro
      - ../../utils/caddy:/etc/caddy-configs:ro
      - ${CONFIGS_DIR:?}/error-pages/dist:/srv/error-pages:ro
      - ${FAST_VOLUMES:?}/ext-proxy/caddy-data:/data
      - ${FAST_VOLUMES:?}/ext-proxy/caddy-config:/config
    networks:
      prom-ext-caddy:
        ipv4_address: 172.21.2.3
      net-ext-homepage:
        ipv4_address: 172.18.2.2
      net-dabloon:
        ipv4_address: 172.18.3.2
      net-authentik:
        ipv4_address: 172.18.4.2
      outgoing:
        ipv4_address: 172.18.0.130
    labels:
      homepage.group: "External"
      homepage.name: "Caddy Reverse Proxy"
      homepage.icon: "caddy.png"
      homepage.description: "Reverse proxy for external services."

networks:
  prom-ext-caddy:
    external: true
  net-ext-homepage:
    external: true
  net-dabloon:
    external: true
  net-authentik:
    external: true
  outgoing:
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.129
